package com.chessv3;

import java.util.*;

/**
 * wraps a two dimensional array of Square elements
 * and acts as proxy to an Iterator
 * generated by the contructor
 */
public class BoardIterator implements Iterator{
	Iterator<Square> iter;
	int index;
	public BoardIterator(Square[][] board){
		ArrayList<Square> arrayList = new ArrayList<Square>();
		for(Square[] row : board){
			for(Square elem : row){
				arrayList.add(elem);
			}
		}
		iter = arrayList.iterator();


	}
	public boolean hasNext(){
		return iter.hasNext();
	}	
	public Square next(){
		return iter.next();
	}
	public void remove(){
		iter.remove();
	}
}
